### ISSUE TITLE
Invalid type

### ISSUE THREAD

**Issue by mlbiche** [prettier/pretty-quick#123]
While using `pretty-quick --staged` on husky pre-commit hook, I am getting the following error :

```
			C:\dev\workspace\humanroads\gps\node_modules\pretty-quick\dist\scms\git.js:60
			throw error;
			^
			TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type object
			at validateString (internal/validators.js:112:11)
			at Object.normalize (path.js:266:5)
			at parseNonShell (C:\dev\workspace\humanroads\gps\node_modules\pretty-quick\node_modules\cross-spawn\lib\parse.js:49:31)
			at Function.parse [as _parse] (C:\dev\workspace\humanroads\gps\node_modules\pretty-quick\node_modules\cross-spawn\lib\parse.js:88:37)
			at handleArguments (C:\dev\workspace\humanroads\gps\node_modules\pretty-quick\node_modules\execa\index.js:28:28)
			at Function.module.exports.sync (C:\dev\workspace\humanroads\gps\node_modules\pretty-quick\node_modules\execa\index.js:162:17)
			at runGit (C:\dev\workspace\humanroads\gps\node_modules\pretty-quick\dist\scms... (show balloon)
```

I am using `pretty-quick@3.1.0` with `npm@7.5.4` on Windows.

Any ideas ? 🤙

**Comment by JounQin** [comment]
A minimal but runnable online reproduction is required.
